wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    session_history: code/_session_history.ipynb
    start_time: 1647426758
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.6
      8:
      - 1
      - 5
max_depth:
  desc: null
  value: 3
tree_method:
  desc: null
  value: gpu_hist
