name: airport_forecasting
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=22.0.2
  - ipykernel
  - pip:
    - scipy==1.7.3
    - numpy==1.22.1
    - matplotlib==3.5.1
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - pandas==1.4.1
    - openpyxl==3.0.9
    - tqdm==4.62.3
    - plotly==5.6.0
    - nbformat==5.1.3
    - tabulate==0.8.9
    - holidays==0.13
    - xlrd==2.0.1
